IMR EQU 21H
EOI EQU 20H     
INT1 EQU 25H
CONT EQU 10H
COMP EQU 11H
ID_TIMER EQU 10

ORG 40
IP_TIMER DW SUBR_CLOCK

ORG 1000H
MSJ DB "Ey muy buenas a todos, "
FIN DB ?

ORG 3000H
SUBR_CLOCK:
MOV BX, OFFSET MSJ
MOV AL, OFFSET FIN - OFFSET MSJ
INT 7
ADD AH, 2 ; DEDUCIMOS QUE CADA 2 SEGUNDOS SE EJECUTRA LA SUBRUTINA, POR LO QUE, SE INCREMENETA EN 2 EL REGISTRO A COMPARAR
MOV AL, 0
OUT CONT, AL
MOV AL, EOI
OUT EOI, AL
IRET

ORG 2000H
CLI
MOV AH, 0
MOV AL, 0FDH
OUT IMR, AL
MOV AL, ID_TIMER
OUT INT1, AL
MOV AL, 2
OUT COMP, AL
MOV AL, 0
OUT CONT, AL
STI
LOOP:
CMP AH, 10 ; VERIFICO SI SE LLEGÓ A LOS 10 SEGUNDOS
JZ FIN_
JMP LOOP
FIN_:INT 0
END