EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H ; LA DIRECCION DE LA INTERRUPCION CON F10 - 
N_F10 EQU 15
ORG 60 ; ORG 60 ES DONDE ESTA EL VECTOR DE INTERRUPCIONES -
IP_F10 DW RUT_F10
ORG 2000H
CLI
MOV AL, 0FEH ; SOLAMENTE ATIENDE LA INTERRUPCIÓN 0
OUT IMR, AL ; LE MANDAMOS LA CONFIGURACIÓN AL IMR -
MOV AL, N_F10 ; LE MANDAMOS A LA INTERRUPCION EL ID -
OUT INT0, AL
MOV DX, 0
STI
LAZO:JMP LAZO
ORG 3000H
RUT_F10:PUSH AX
INC DX ; INCREMENTO EL CONTADOR -
MOV AL, EOI
OUT EOI, AL ; MANDO AL EOI EL VALOR DE AL -
POP AX
IRET
END