EOI EQU 20H
IMR EQU 21H
INT2 EQU 26H
DATO EQU 40H
ESTADO EQU 41H
ID_INT2 EQU 15

ORG 1000H
LONGITUD DB 5
MSJ DB ?

ORG 60
IP_IMP DW SUBR_IMP

ORG 3000H
SUBR_IMP:
PUSH AX ; SALVO AX
MOV AL, [BX] ; OBTENGO EL CHAR
OUT DATO, AL ; LO MANDO AL BUS DE DATOS
INC BX ; AVANZO DE POSICION
DEC DH ; DECREMENTO PARA SABER CUANDO FINALIZAR
JNZ SEGUIR

TERMINAR:
MOV AL, 0FFH ; DESACTIVO LAS INTERRUPCIONES
OUT IMR, AL

SEGUIR:
MOV AL, EOI ; AVISO AL PIC
OUT EOI, AL
POP AX
IRET

LEER: ; SUBRUTINA PARA LEER EL MENSAJE A IMPRIMIR
MOV AH, LONGITUD 
MOV BX, OFFSET MSJ
LOOP_LEER:
INT 6
INC BX
DEC AH
JNZ LOOP_LEER
RET

ORG 2000H
CLI
CALL LEER ; LLAMO A LA SUBRUTINA
MOV AL, 0FBH ; ACTIVO LA INT2
OUT IMR, AL
MOV AL, ID_INT2 ; INFORMO EL ID
OUT INT2, AL
MOV DH, LONGITUD ; MUEVO LA LONGITUD A DH PARA DECREMENTAR EN LA SUBR DE LA IMPRESORA
STI

MOV BX, OFFSET MSJ ; OBTENGO LA DIR DEL MENSAJE
IN AL, ESTADO ; LEO EL ESTADO
OR AL, 80H ; ACTIVO LA INTERRUPCION
OUT ESTADO, AL

LOOP:
CMP AH, 0 ; VERIFICO SI AH ES 0
JZ FIN ; SI ES 0 FINALIZO
JMP LOOP

FIN:
IN AL, ESTADO
AND AL, 7FH ; DESACTIVO LA INTERRUPCION
OUT ESTADO, AL
INT 0
END