DATO EQU 40H
ESTADO EQU 41H
ORG 1000H
MSJ DB "EL HANDSHAKE ES LA CABRA"
FIN DB ?
ORG 300H
IMPRIMIR_CARACTER:
IN AL, ESTADO ; ENTRO AL POLL Y VERIFICO EL ESTADO
AND AL, 1 ; SI EL PRIMER BIT ES 1 LOOPEO, SI NO, SIGO
JNZ IMPRIMIR_CARACTER
MOV AL, [BX] ; LE MANDO EL CARACTER
OUT DATO, AL ; LE ENVIO EL CARACTER AL BUS DE DATOS
INC BX ; INCREMENTO LA POSICION DEL MENSAJE
CMP BX, OFFSET FIN ; VERIFICO SI LLEGUÉ AL FINAL
JNZ IMPRIMIR_CARACTER ; SI LLEGUE TERMINO, SI NO VUELVO AL POLL
RET
ORG 2000H
LOOP:
IN AL, ESTADO ; TOMO EL VALOR DEL ESTADO
AND AL, 01111111B ; APLICO EL AND PARA EL METODO DE INTERRUPCION Y NO PISAR EL ESTADO INICIAL
OUT ESTADO, AL ; ENVIO NUEVAMENTE EL ESTADO
MOV BX, OFFSET MSJ
CALL IMPRIMIR_CARACTER
INT 0
END